AWSTemplateFormatVersion: '2010-09-09'
Description: "IAM Role and Instance Profile for CloudWatch and SSM"
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Instance Profile Role'
      Parameters:
      - Rolename
Parameters:
  Rolename:
    Description: 'IAM Instance Profile Role Name '
    Type: String
    Default: ''

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref Rolename
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: !Ref Rolename
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Ref Rolename
      Path: "/"
      Roles:
        - !Ref InstanceRole